### ISSUE TITLE
media-sound/carla implement 32 bit VST support

### ISSUE THREAD

**Issue by mercuriete** [q-g-j/qgj-overlay#1]
I was able to compile carla using a derived ebuild from your overlay

I put this:
```
	if use vst; then
		emake win64 \
			CC=$(find /usr/bin/x86_64-w64-mingw32-gcc-9* | tail -n1) \
			CXX=$(find /usr/bin/x86_64-w64-mingw32-g++-9* | tail -n1)
		emake wine64
		emake win32 \
			CC=$(find /usr/bin/i686-w64-mingw32-gcc-9* | tail -n1) \
			CXX=$(find /usr/bin/i686-w64-mingw32-g++-9* | tail -n1)
		emake wine32
	fi
```

and it works for me.

I was able to run win32 VST using wine.
Thanks for your amazing work.

PS: you can see I am using mingw gcc:9 ... I don't know really why I couldn't compile mingw gcc:10 but crossdev installed version 9 instead.

**Comment by q-g-j** [comment]
That's a good hint; I forgot, that I have set the ~amd64 keyword for **cross-x86_64-w64-mingw32/gcc**. The last stable version is still v9 which also works for Carla.
I updated the ebuild in my overlay with your win32 part and dropped the **cross-x86_64-w64-mingw32/gcc** dependency check, cause this can only be installed manually with crossdev.

EDIT: forgot to run git push, now it should be online

**Comment by mercuriete** [comment]
I didn't try your ebuild but I saw the commit and it looks fine.
You can close this issue.
Thank you very much.
